"""Added likes column to Image model

Revision ID: 704a155775c9
Revises: 
Create Date: 2024-07-11 15:11:22.059643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704a155775c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('likes')

